# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: yarn install
          command: |
            yarn config set cache-folder .cache/yarn
            yarn install --prefer-offline --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
            - .cache/yarn
          key: v3-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn run lint packages/*/src
      - run: yarn run build
      - run: yarn run test:ci -- -- --maxWorkers=2

      # only run coverage if repo token is available (so third parties don't fail the build)
      - run:
          name: coverage
          command: |
            cd packages/rest-hooks
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then yarn run test:coverage --maxWorkers=2 --coverageReporters=text-lcov | yarn run coveralls; fi
  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -t -v $(pwd):/home/repo coinbase/salus

workflows:
  version: 2
  build:
    jobs:
      - build
      - salus
