name: Benchmark

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run benchmark
      run: yarn install && yarn bench | tee output.txt
    - name: Download previous benchmark data
      uses: actions/cache@v2
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    # PR comments on changes
    - name: Store benchmark result
      if: ${{ github.event_name == 'pull_request' }}
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'benchmarkjs'
        output-file-path: output.txt
        external-data-json-path: ./cache/benchmark-data.json
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '150%'
        comment-always: true
        fail-on-alert: false
        alert-comment-cc-users: '@ntucker'
        # we only want to compare against master, so do not save for PR
        save-data-file: false

    # master reports to history
    - name: Store benchmark result
      if: ${{ github.event_name == 'push' }}
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'benchmarkjs'
        output-file-path: output.txt
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        gh-pages-branch: 'gh-pages-bench'
        auto-push: true
        fail-on-alert: false
